name: Label Dependabot PR
'on':
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
jobs:
  labels:
    runs-on: ubuntu-latest
    if: 'startsWith(github.event.pull_request.user.login, ''dependabot'')'
    steps:
      - uses: jurijzahn8019/action-dependabot-bump-range@v0.0.11
        id: checker
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Add Pull Request Label for Major Updates
        uses: actions-ecosystem/action-add-labels@v1
        if: steps.checker.outputs.diff == 'major'
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          labels: 'pull: not merge'
      - name: Add Pull Request Label for Version Diff
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          labels: 'dependency: ${{ steps.checker.outputs.diff }}'
